### PR TITLE
Add tilesets and a way to cycle through them

### PR DESCRIPTION
**Pull request by eliot-akira**
Hi, thank you for sharing such a fun project. We briefly exchanged comments on a [recent HackerNews thread](https://news.ycombinator.com/item?id=40693944) about SimCity in the browser, Chaim Gingold's PhD thesis and new book, cellular automata, [Von Neumann universal constructor](https://en.wikipedia.org/wiki/Von_Neumann_universal_constructor), smart goo.

Here's a pull request I hope you'll like. It adds:

- a set of tileset images: Asia, Earth, Future, Medieval, Moon, Snow, Wild West
- keyboard shortcuts to cycle next/previous tileset, tentatively assigned to `+` and `-`

---

As a long-time fan of SimCity, I've explored different ways to keep playing with the concept - including [SimCity v1.4 on emulated Macintosh System 6 in the browser](https://eliotakira.com/simcity/) (loud beep on boot), and rewriting a JavaScript port called MicropolisJS into my own [Microcity](https://github.com/eliot-akira/microcity/). It's been a fun way to learn about SimCity's internal algorithms and data structures.

Another hobby project I have is software preservation of [Neko](https://github.com/eliot-akira/neko), a kind of "software pet" created in Japan in the 1980's, that has been ported to many platforms including the web. It was interesting to hear you mention virtual pets in relation to von Neumann's 29-state cellular automata.

> These have been digitally implemented in the real world on modern computing machinery, and they make great **virtual pets, kind of like digital tribbles**..

So I see how SimCity and Neko are related, they're both "idle games" of state machines with life-like behavior. [On the Design of Idle Games.pdf](https://github.com/user-attachments/files/15874623/On.the.Design.of.Idle.Games.pdf)

### CODE REVIEW

**Review by SimHacker — APPROVED** [review]
Awesome, this will really look cool in the Space Inventory! Thank you!

**Comment by SimHacker** [comment]
It's live!!! The Space Inventory looks even weirder now! 
I added key synonyms for - or _ and = or + so you can use the shift key or not. 
I'll make an announcement with some cool screen snapshots. Do you have a twitter account you want @'ed for credit?

**Comment by SimHacker** [comment]
Also what's your email and hacker news account, please, if you like? 
I was recently visiting Prague with my brother, and we had a fantastic time!
I really love hacking in the old cafes there.

**Comment by SimHacker** [comment]
Here is an unlisted youtube video (I don't have permission to publically distribute the music by Jarry Martin, who made the music for The Sims and various versions of SimCity (not Classic though it didn't have any music). I've asked him for permission to use some of his music, and maybe I can distribute it on the web site or with the game, or at least use it in some videos. This shows the space inventory, with the new tile sets! Thanks a lot, they really add a lot to the game and the space inventory too! 

https://www.youtube.com/watch?v=319i7slXcbI

**Comment by eliot-akira** [comment]
How serendipitous it seems, just now I found an old article you wrote about using XML as a scripting language: "[Applying XML to Describing User Interface Layouts and Behavior and Constraints](https://web.archive.org/web/20080226021907/http://www.donhopkins.com/drupal/node/105)".

For several years I've been developing a product that's very similar in concept, a template language based on an extended HTML sytanx, called [Loops & Logic](https://loopsandlogic.com/). It's not as strict as XML, with a more forgiving HTML parser, which might be easier for beginners.

Anyway, I hope to follow along with the progress of Micropolis Web, and maybe find a way to contribute/collaborate somehow.

**Comment by SimHacker** [comment]
Holy Plate of Shrimp!

I just send an email to Paul Haberli a few days ago to get back in touch, telling him about how the tldraw web based drawing tool is being integrated with AI and visual programming languages. 

That visual programming system built on top of tldraw was inspired by Alexey Radul's propagator model from his 2009 paper. Alexey was Gerald Jay Sussman's student.

The thread’s at the end, which will show you all about tldraw and the visual programming language that somebody did with it. 

I’m definitely looking forward to collaborating — we already are: your code’s deployed and I’ve been using and recording it already! 

The tile sets call for a pie menu to switch between sets, with pretty icons for each style. 

So I’m overhauling my crusty 11-year-old JavaScript jQuery pie menus (which are getting bit stale) and rewriting them in TypeScript with modern SvelteKit (its architecture is quite different and much much better, so they will give designers a lot of flexibility and power to use SVG and CSS and HTML “snippet” templates to customize them! 

And of course each tile set needs its own set of appropriately styled pie menus with the labels and icons for the building tools reflecting the tile set. 

What if there were a few more bits in the map tiles to select and lock the tile set, so your city could incorporate lots of different tile sets at once, which would be super useful for plug-in zones and even painting tools!

Each tile set could have a non-zero id, and tile set id 0 would just show through to the currently selected tile set. 

Then you could build zones, roads, rails, parks, etc, with a “sticky” tile set bit, that stayed in the same tile set after you switched! Or just paint the “lock tile set” bit over existing zones or land to keep them in that tile set after you change.

You could also use the black and white tile set to temporarily highlight uninteresting parts of the map, while showing other interesting tiles in full color (like the population density or traffic maps).

Ben Shneiderman came up with the great idea of a “dynamic home finder” for “rapidly, incrementally, and reversibly” searching maps for real-estate listings, which I adapted to SimCity, which could use that technique. 

Dynamic queries demos: revised HomeFinder and text version plus health statistics atlas (1994)

https://www.youtube.com/watch?v=NNjXsgB8ix8

SimCity Frob-O-Matic Dynamic Zone Filter:

https://youtu.be/_fVl4dGwUrA?t=216

All the supporting code for this is still there, it just needs to be hooked up. 

It needs to support multiple map views, and data overlays. No need for special small tile rendering like the original version has, since it can render an entire scaled map of tiles so quickly. It just needs to support multiple views with overlays and tile set highlighting. 

I think the black-and-white unhighlighted, color (possibly tinted) tiles on the map changing rapidly and incrementally and reversibly in response to adjusting the query parameters will be breathtaking! 

An ambitious goal I have for Micropolis is to integrate it with Snap!

I sent this to Jens Mönig, Snap’s author:

How would I hook this up to Snap! ? Is there a way for the new snap in snap stuff to slurp in a javascript module and call it, or should my javascript module slurp in snap and call it?

-Don

**Comment by SimHacker** [comment]
Inspiring software alert!!!

I can’t say enough about how awesome tldraw is, and how cool the people working on it are.

Take a deep dive! They make lots of eight-second demos that will blow your mind like a pan of jiffy pop popcorn! Or the final scene in Real Genius. 

Check out their amazing demos of using ChatGPT to iteratively render and refine wireframe drawings as working interactive html+css+JavaScript user interfaces! Truly the cutting edge of programming by demonstration!

https://x.com/tldraw

Once of my favorites -- "dance for me, boys!":

https://x.com/tldraw/status/1795778945117290628

James Landay replied: "And as usual, these people don’t understand why
it is valuable as a sketch… must be engineers…"

James Landay, I can't resolve your pronouns, what do you mean by "it"
and "these"? Do you mean generating user interfaces inside the drawing
tool itself, instead of as stand-alone embedded html applications?
They're doing that too! A lot like HyperCard, and Brett Victor's
"Drawing Dynamic Visualizations".

https://x.com/OrionReedOne/status/1792812569935188431

Also somebody's working on implementing a visual
programming system inspired by Alexey Radul's propagator model from
his 2009 paper. Alexey was Gerald Jay Sussman's student.

https://x.com/dennizor/status/1794065248984396013

Revised Report on the Propagator Model, Alexey Radul and Gerald Jay
Sussman:

https://groups.csail.mit.edu/mac/users/gjs/propagators/

He's also used that to define a basic cellular automata called a
'binary network':

https://x.com/dennizor/status/1795601405065216027

Also a very nice way to visually program JavaScript:

https://x.com/tldraw/status/1794302687577845973

Here's a simple shoot-em-up computer game defined by wireframes and
annotations and generated by ChatGPT -- note that you can iteratively
refine it by making more annotations and drawings over the finished
product, and it looks at the previous examples and makes a new
version:

https://x.com/tldraw/status/1792910208911413747

I love this one: It implements a webcam view with a snapshot button and scrolling list of snapshots, from a wireframe spec:

https://x.com/tldraw/status/1792586961946816533

Some of the people working on tldraw are also artists as well as engineers:

📺 Screens in Screens in Screens

https://www.youtube.com/watch?v=Q4OIcwt8vcE

James Landay replied: "the value in leaving the sketch as an interactive
interface rather than converting it to hi-fi working html."

Yes I totally agree, that's the way to go! The LLM already has a
strong grasp of generic widely known html/css/JavaScript APIs so it's
easy to make stand-alone apps, but you could include a concise
description of the drawing tool APIs (JSON schemas, JS classes,
TypeScript declarations (which are great for JSON structures as well
as method signatures, and well understood), etc) in the prompt, to
make it target the sketch instead of generic HTML. The art is in
coming up with llm-friendly sketch tool apis that are crisp and
concise enough to fit in the prompt. Either that or making an open
source drawing tool that's popular and well documented enough that
LLMs learn from its source and docs (easy to say, hard to do, but
tldraw has a great start on that). Prompt window size is getting
pretty big now, and growing, but there will always be pressure to
conserve tokens. The long term solution is to define standard widely
known drawing tool APIs that LLMs can be trained on so you don't have
to spend the prompt on that. For example they already know tailwind
CSS conventions. Here's the prompt that tldraw's "Make Real" button
uses:

https://github.com/tldraw/make-real/blob/main/app/prompt.ts

export const OPEN_AI_SYSTEM_PROMPT = "
You are an expert web developer who specializes in building working
website prototypes from low-fidelity wireframes. Your job is to accept
low-fidelity designs and turn them into interactive and responsive
working prototypes. When sent new designs, you should reply with a
high fidelity working prototype as a single HTML file.

Use tailwind CSS for styling. If you must use other CSS, place it in a
style tag.

Put any JavaScript in a script tag. Use unpkg or skypack to import any
required JavaScript dependencies. Use Google fonts to pull in any open
source fonts you require. If you have any images, load them from
Unsplash or use solid colored rectangles as placeholders.

The designs may include flow charts, diagrams, labels, arrows, sticky
notes, screenshots of other applications, or even previous designs.
Treat all of these as references for your prototype. Use your best
judgement to determine what is an annotation and what should be
included in the final result. Treat anything in the color red as an
annotation rather than part of the design. Do NOT include any of those
annotations in your final result.

Your prototype should look and feel much more complete and advanced
than the wireframes provided. Flesh it out, make it real! Try your
best to figure out what the designer wants and make it happen. If
there are any questions or underspecified features, use what you know
about applications, user experience, and website design patterns to
"fill in the blanks". If you're unsure of how the designs should work,
take a guess—it's better for you to get it wrong than to leave things
incomplete.

Remember: you love your designers and want them to be happy. The more
complete and impressive your prototype, the happier they will be. Good
luck, you've got this!"

export const OPENAI_USER_PROMPT = "
Here are the latest wireframes. There are also some previous outputs
here. We have run their code through an 'HTML to screenshot' library,
that attempts to generate a screenshot of the page. The generated
screenshot may have some inaccuracies, so use your knowledge of HTML
and web development to figure out what any annotations are referring
to, which may be different to what is visible in the generated
screenshot. Make a new website based on these wireframes and notes and
send back just the HTML file contents."

I've been marking up the interface declarations in my TypeScript code
with // *** BEGIN PROMPT FooBar *** ... // *** END PROMPT FooBar ***
and including copious comments aimed at both humans and LLMs, so I can
have one single source of truth that I extract from the code and
include in prompts, so the LLM knows exactly what to produce to
dovetail with the actual code, without actually having to feed it all
of the code in the prompt, just the important stuff with specific
instructions in the comments.

**Comment by eliot-akira** [comment]
mind_blown

An intellectual feast - lots of interesting ideas, reading and thinking material.

[tldraw](https://github.com/tldraw/tldraw) is a great example of the kind of interactive "computational medium" that Alan Kay, Bret Victor and others have been advocating. I love how seamlessly they're integrating LLM/generative art while keeping the interface simple. Like a visual conversation, shaping and sculpting the medium with an intelligent tool/assistant that understands language and design.

It reminds me of the work going on at Ink & Switch, like [Programmable Ink](https://www.inkandswitch.com/inkbase/), [Dynamic documents as personal software](https://www.inkandswitch.com/potluck/), and [End-user programming](https://www.inkandswitch.com/end-user-programming/). It also fits well with Future of Coding and their [Whole Code Catalog](https://futureofcoding.org/catalog/) of innovative programming paradigms and interfaces.

---

> Also somebody's working on implementing a visual programming system inspired by Alexey Radul's propagator model from his 2009 paper. Alexey was Gerald Jay Sussman's student.

This nugget led me down a rabbit hole, starting with [Propagation Networks: A Flexible and Expressive Substrate for Computation](https://dspace.mit.edu/handle/1721.1/49525).

> I propose a shift in the foundations of computation. Practically all ideas of general-purpose computation today are founded either on execution of sequences of atomic instructions, i.e., assembly languages, or on evaluation of tree-structured expressions, i.e., most higher level programming languages.
>
> Both have served us well in the past, but it is increasingly clear that we need something more. I suggest that we can build general-purpose computation on propagation of information through networks of stateful cells interconnected with stateless autonomous asynchronous computing elements.

If I understand correctly, this sounds like how cells in Excel spreadsheets work. And reactive cells in computational notebooks like [Jupyter](https://jupyter.org/) and [Observable](https://simonwillison.net/2024/Mar/3/interesting-ideas-in-observable-framework/). Maybe also similar to [Conway's game of life](https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life), or even the SimCity/Micropolis simulation, how each tile affects its surrounding tiles, leading to emergent behavior.

[Revised Report on the Propagator Model](https://groups.csail.mit.edu/mac/users/gjs/propagators/) is deep. I'll enjoy reading this in detail. So Alexey Radul studied under [Gerald Jay Sussman](https://en.wikipedia.org/wiki/Gerald_Jay_Sussman), author of [Structure and Interpretation of Computer Programs](https://en.wikipedia.org/wiki/Structure_and_Interpretation_of_Computer_Programs), who in turn studied under [Seymour Papert](https://en.wikipedia.org/wiki/Seymour_Papert) and [Marvin Minsky](https://en.wikipedia.org/wiki/Marvin_Minsky).

---

[Ben Shneiderman](https://en.wikipedia.org/wiki/Ben_Shneiderman) you mentioned before, I see he was an influential thinker on human-computer interaction and user interface design. I especially like his idea on "direct manipulation interface":

> ..an approach to interfaces which involves continuous representation of objects of interest together with rapid, reversible, and incremental actions and feedback.
>
> ..to allow a user to manipulate [objects](https://en.wikipedia.org/wiki/Object_(computer_science)) presented to them, using actions that correspond at least loosely to manipulation of physical objects.
>
> An example of direct manipulation is resizing a graphical shape, such as a rectangle, by dragging its corners or edges with a mouse.

Right, the SimCity Frob-O-Matic Dynamic Zone Filter (expialidocious) is an example of this, how moving the sliders immediately queries the data layers and shows the result on the map. That's an effective way to surface interesting insights into the usually invisible "living data" percolating under the surface. I can see how it's a way of making instant database queries as you adjust the parameters.

This immediate feedback is so key in giving the feeling of direct manipulation. It's the same with developer tools, like changing CSS style properties and seeing the result instantly in the web document. It's what I'm trying to achieve with the template language. Oh, I want to show a cool thing I made. :)

loops and logic with atomic css

The preview is showing the result of rendering the template, which includes a database query using `<Loop>`.

---

Speaking of templates, I enjoyed seeing how Svelte works. I usually work with React, so it was refreshing to see a templating language of different design.

> What if there were a few more bits in the map tiles to select and lock the tile set, so your city could incorporate lots of different tile sets at once, which would be super useful for plug-in zones and even painting tools!

Ooh, I had this idea too, it would be cool if the map supported multiple tilesets at the same time.

> Once the UI is fleshed out, the next interesting part will be implementing the plug-in system so you can make plug-in robots and zones in JavaScript!

For robots, it'd be fun if I could bring Neko creatures into Micropolis.

neko variants

I have a collection of icon sets for these variants, so I want to bring them back to life and let them run around on the screen. They're a kind of Sim creature with primitive thinking process and behaviors. I always thought it would be cool to let people create their own creatures and program them in a visual programminng environment.

When you mentioned "plugin", it made me think of WebAssembly. That would let people to write plugins in any language that compiles to WASM. And they would run in a safe sandboxed environment.

---

An aspect of Micropolis Web that I like is how you isolated the engine from the interface. The WASM part is like **headless SimCity**, so the engine could theoretically be hooked up to different views, or multiple instances running at the same time. It makes the game more programmable.

> you could include a concise description of the drawing tool APIs (JSON schemas, JS classes, TypeScript declarations (which are great for JSON structures as well as method signatures, and well understood, etc) in the prompt, to make it target the sketch instead of generic HTML. The art is in coming up with llm-friendly sketch tool apis that are crisp and concise enough to fit in the prompt.

This makes me think, I suppose the Micropolis engine is the low-level interface, and there would a higher-level public interface, an API for plugins, robots, Snap, LLM.

**Comment by SimHacker** [comment]
Yes, that's exactly how I see tldraw: as a computational platform, not just a drawing tool.

In many ways HyperLook was a lot like that, too, and porting SimCity to it was a great exercise in integrating graphics, animation, zooming, multiple views, a PostScript drawing editor, pie menus, all together in an extensible scriptable graphical platform that users could customize and build on top of. 

Chaim Gingold designed these SimCity Reverse Diagrams while he was working at HARC with Alan Kay and Brett Victor, with the intent that they be developed into interactive diagrams like the visualizations that Brett talks about. 

https://smalltalkzoo.thechm.org/users/Dan/uploads/SimCityReverseDiagrams.pdf

The text at the bottom of the diagrams says it explicitly:

"If we merge the reverse diagram with an interactive approach—e.g. Bret Victor’s Nile Visualization
(Victor 2013), such diagrams could be used generatively, to describe programs, and interactively,
to allow rich introspection and manipulation of software."

I've been discussing tldraw with Chaim and he gave me permission to work on a live interactive version of his SimCity Reverse Diagrams that are integrated with Micropolis. The natural thing to do would be to plug Micropolis into tldraw as a component that can be connected to and generate live drawings and user interfaces. Why not use tldraw for the entire user interface and visualization dashboards? 

https://smalltalkzoo.thechm.org/users/Dan/uploads/SimCityReverseDiagrams.pdf

I'm currently using SvelteKit for Micropolis, not React, but I recently ran across a tutorial on integrating Svelte components into React apps, and it's actually quite easy. 

I owe a lot to Ben Shneiderman -- I worked with him at the University of Maryland Human Computer Interaction Lab, and one of his students, Jack Callahan, performed an empirical evaluation of pie versus linear menus, which we published at CHI'88. His compassionate approach and writing style have always inspired me. He named his lab the Human Computer Interaction Lab, and he refers to the field as HCI instead of CHI (like the ACM special interest group arranges the letters), because Humans come before Computers! His definition of Direct Manipulation as "continuous representation of objects of interest together with rapid, reversible, and incremental actions and feedback" was in the front of my mind when I designed the architectural editing and object manipulation tools and pie menus in The Sims. He's also done some great work with info visualizations, like the dynamic home finder I mentioned, treemaps, and many other cool things! 

The Sims, Pie Menus, Edith Editing, and SimAntics Visual Programming Demo:

https://www.youtube.com/watch?v=-exdu4ETscs

Very cool templating language! I did a bunch of work with OpenLaszlo, which was like JavaScript wrapped in XML, kind of like Adobe Flex, but cross platform, and a lot more advanced because it had constraints (like reactive programming) and data binding. It was from before JSON took over from XML. Another XML templating/programming language I've used a lot and really love is Genshi, which is based on Python. Here are some links to stuff I've written about those on Hacker News:

OpenLaszlo and "Instance First Development":

https://news.ycombinator.com/item?id=21841054

What I love about Genshi, and a comparison of OpenLaszlo to Garnet, a constraint based (i.e. reactive) user interface system written in Common Lisp that I worked on with Brad Myers at CMU back in 1992:

https://news.ycombinator.com/item?id=29953932

Now back to Micropolis:

I have been working on the tile renderer to improve the support for tile sets and data visualization! 

I added another 16 bit integer map layer that I call the "mop" layer, that parallels the 16 bit integer map. If you load a save file with no mop, it clears it to zero, and when you save a new file, it writes out the mop after the map. 

To start with, I'm using the lower 4 bits to select the tile set on a tile-by-tile basis. So it will be possible to have a city that combines a bunch of different tile sets! This is an essential step towards supporting plug-in user defined tiles, zones, etc. And also extremely useful for data visualization! 

For example, the old Frob-O-Matic Dynamic Zone Filter would "lowlight" the uninteresting tiles by replacing them with dirt. Now it will be able to lowlight tiles by selecting the old black-and-white tile set! So to that end I booted up a Mac emulator with SimCity and ResEdit, opened up the black and white tiles, took a screen snapshot, and made a new tile set. 

At first I tried passing the different tile sets to the shader by passing an array of textures. The array has to be fixed size, and there are some limitations on how your shader program can index the array of textures! It supports constant indexes, but not variables! So you have to make a switch statement, which is gross, but works. However it limits you to 16 textures, and I'm already using two for the map and the mop, so that leaves only 14 more textures, which is enough for the 9 tile sets, but not enough to support plugins. 

So I fixed it to take tall textures with multiple tile sets per texture, and made a "all" tileset texture with all 9 tile sets, and that works: now you can select any tile set for any tile in the mop layer! 

I left in the support for 8 layers, so we can use layers for other purposes, like hires and lores tile set layers, or transparent glyph overlays, etc.

Plug-in tiles and zones will be able to register their tiles and they can be dynamically laid out into a dynamic texture layer. I'll implement a tile index mapping array so you can virtualize the tile index => texture position mapping. The old Python/C++/cairo tile engine had that feature, but it could call back to a Python function to perform arbitrary dynamic tile mappings, but that's not possible to call back from a shader to JavaScript, so it'll simply use a lookup table.

The other important plug-in interface is for creating and programming agents like the tornado, helicopter, airplane, godzilla, pacbot, and those characters in your sprite sheet! 

I think those will be easy enough to handle in a canvas 2d or SVG layer above the WebGL canvas, and don't need to be implemented in the shader. 

I will be really exciting to integrate Micropolis with Snap! so it uses Snap sprites as Micropolis agents, that you can program with visual block code! 

It should be possible to implement plugins in separate WebAssembly modules as well as in JavaScript. It's easiest to just use JavaScript since no compilation is required, I think. Of course you could also write C++ extensions to Micropolis (like I am doing to add the mop layer), but that is not as flexible and runtime live codable as using JavaScript! 

Multiple views are definitely on the roadmap, too! 

I also want to stream analytics (all the stuff SimCity displays in the history graph, evaluation, RCI gauges, financial windows, plus all the internal events and simulation parameters) as JSON out to a time series database like Prometheus, so we can make Grafana dashboards to monitor and visualize and analyze it in real time! 

-Don

**Comment by SimHacker** [comment]
Oh yeah forgot to mention: I'm in the process of overhauling my crusty 11-year-old jQuery pie menus in TypeScript for Svelte. I think it will be possible to plug the Svelte pie menu component, as well as the Micropolis simulator and views themselves, into TLDraw by making a TLDraw extension that has a React adaptor wrapper. 

Jack Herrington has a great tutorial describing how to do that here:

https://www.youtube.com/watch?v=FrusJNycQvk

He's using an older version of Svelte, and an independent state management system called zustand to share data. 

I'm using the latest version of Svelte 5 with Runes, but it should be straightforward to adapt Svelte 5 to use whatever state management system that tldraw and React are using.

**Comment by eliot-akira** [comment]
The monochrome tileset is lovely, it's got that retro nostalgia of early Macintosh.

monochrome

I'm reading Bret Victor's [Media for Thinking the Unthinkable](https://worrydream.com/MediaForThinkingTheUnthinkable/) and watching [the talk](https://www.youtube.com/watch?v=oUaOucZRlmE&t=212s) again, where he demonstrates a scientific paper with interactive diagrams.

bret victor media for thinking the unthinkable - screenshot

> If we merge the reverse diagram with an interactive approach—e.g. Bret Victor’s Nile Visualization (Victor 2013), such diagrams could be used generatively, to describe programs, and interactively, to allow rich introspection and manipulation of software.

Now I'm picturing Chaim's diagrams hooked up to the Micropolis engine, with each diagram as a tiny "city" instance.

micropolis - create traffic

Then I suppose there could be many instances of cities running in a single page, like an article with diagrams. This relates to something I've been exploring, how to let people write articles with dynamic blocks such as music notation (playable pieces of sheet music), fretboard and keyboard diagrams.

A thought I had, maybe the Micropolis engine can be seen as a virtual machine that evaluates an expression. With a given map as initial environment, and actions/methods to modify the world state. That seems to fit with your insight about Snap being a Scheme, so that a Chaim diagram, or modular city instance, is like a Lisp program on the Micropolis runtime.

---

About the pie menu, the way you've described it sounds like it would fit well with the React paradigm.

> The idea is that it will be configured by a big json tree, that can include top level and sub pie menus, which contain slices, which contain items, with various parameters and tracking callbacks, which can be laid out and rendered with labels, icons, svg graphics, etc.

Especially this part about each menu item being a "rich component", possibly containing nested child menu items. This tree-structure of components is exactly how React works, in particular keeping that tree synced with changing state, as they say, "view as a function of state".

state view action

> stream analytics (all the stuff SimCity displays in the history graph, evaluation, RCI gauges, financial windows, plus all the internal events and simulation parameters) as JSON out to a time series database

That's a fun idea, I picture a Micropolis API where you can subscribe to event streams.

..A further thought comes to mind, about how people could run their own Micropolis servers, or instances, and broadcast their city like an RSS feed.

There could also be a personal dashboard of Micropolis stats, with moving graphs and charts like a Bloomberg terminal.

Bloomberg-Pro-Terminal-scaled-1

**Pull request merged**
